name: Publish to TestPyPI
on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine build
          pip install -r requirements.txt
          pip install pytest
      - name: Test with pytest
        run: |
          pytest tests -v
      - name: Build and publish to TestPyPI
        run: |
          # Install the package from setup.py
          python3 -m build
          python3 -m twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
